export const FETCH_ACTIVITIES = "fetch_activities";
export const FETCH_THIS_YEAR = "fetch_this_year";
export const FETCH_CODE = "fetch_code";
export const FETCH_GOAL = "fetch_goal";
export const LOG_OUT = "log_out";
export const LOG_IN = "log_in";
export const CALLBACK_URI = "winteredition.io";
export const FETCH_AUTHORIZATION_TOKEN = "fetch_authorization_token";
//export const ACCESS_TOKEN = "6e2a2235746a4f1adfcae7bcb0e346f95fa4e685"; //this is from my page?
export const ACCESS_TOKEN_MINE = "fa10bcce4e1eff5a5048d1a063eba69c42320a28"; //this is from my page?